In [1]:
import numpy as np

# Basic Operations

In [12]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [13]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
# Get dimension
b.ndim

2

In [15]:
# Get Shape
b.shape

(2, 3)

In [16]:
# Get Type
print(a.dtype)
b.dtype

int16


dtype('float64')

In [17]:
# Get size in bytes
a.itemsize

2

In [18]:
# Get total size in bytes
a.nbytes

6

# Accessing & Changing Arrays

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element
a[1, 5]

13

In [21]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specifc column
a[:, 2]

array([ 3, 10])

In [24]:
# Get all even numbers in row (example)
a[0, 1::2]

array([2, 4, 6])

In [26]:
# Changing an element
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [27]:
# 3-D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Get specific element
b[0, 1, 1]

4

In [30]:
# Changing elements
b[:, 1, :] = [[9,9],[8,8]]  # dimensions must match!
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [32]:
# All zeros matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
# All ones matrix
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# Any other number
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [36]:
# Fills an array with a number with the same size as the reference array
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [37]:
# Random decimal numbers
np.random.rand(3,3)

array([[0.19342909, 0.83065692, 0.64006126],
       [0.08735691, 0.37520261, 0.31247931],
       [0.6276264 , 0.68621002, 0.06396377]])

In [38]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[5, 4, 4],
       [0, 3, 4],
       [3, 5, 2]])

In [39]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# Repating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
# Initialization challenge
arr = np.ones((5,5))
arr[1:4, 1:4] = np.zeros((3,3))
arr[2,2] = np.full((1,1), 9)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
# Copying arrays
a = np.array([1,2,3])
b = a.copy() # b = a will cause b to point to a.
print(b)

[1 2 3]


# Mathematical Operations

### Basic operations

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
a + 2

array([3, 4, 5, 6])

In [54]:
a - 2

array([-1,  0,  1,  2])

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [58]:
a + b

array([2, 2, 4, 4])

In [59]:
a ** 2

array([ 1,  4,  9, 16])

In [60]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear algebra 

In [64]:
a= np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [65]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [67]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats, axis = 1)

array([3, 6])

In [70]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganinzing arrays

In [72]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [74]:
# Vertically stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
# Horizontally stacking matrices
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Load Data from a File

In [83]:
# example file is comma delimited
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking & Advanced Indexing

In [84]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [85]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [86]:
# Lists can be used to access multiple elements in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,4,-1]]

array([1, 5, 9])

In [87]:
np.any(filedata > 50, axis = 0)  # Check if there is a value greater than 50 in each column.

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [89]:
np.all(filedata > 50, axis = 0)  # Check if all values are greater than 50 in each column.

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [90]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [92]:
# Indexing challenge
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],
       [26,27,28,29,30]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [102]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [111]:
arr[[0,1,2,3],[1,2,3,4]]  # <list of row indexs> <list of column indexes>

array([ 2,  8, 14, 20])

In [112]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])