# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
arr = np.zeros(10)
print(arr, arr.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 10


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
arr = np.random.randint(10, 50, size=10)
print(arr)

[45 15 39 43 44 11 32 22 44 18]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
print(arr[::-1])

[18 44 22 32 11 44 43 39 15 45]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
arr = np.random.randint(9, size=(3, 3))
print(arr, arr.shape)

[[0 7 2]
 [4 5 0]
 [0 3 4]] (3, 3)


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [7]:
arr = np.array([1,2,0,0,4,0])
print(arr.nonzero()[0])

[0 1 4]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
arr = np.random.randint(101, size=(3, 3, 3))
print(arr, arr.shape)

[[[74 16 22]
  [70 52 87]
  [60 50  0]]

 [[23 42 50]
  [24 58 66]
  [ 9 47 93]]

 [[12 83 39]
  [81  9 46]
  [ 4  0 58]]] (3, 3, 3)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [9]:
arr = np.random.randint(101, size=(10, 10))
print(arr, arr.shape)
print(f"min = {arr.min()}, max = {arr.max()}")

[[ 59  43  80  88   7  43  39  52  97  47]
 [ 90  16  52  63  30  66  72  38  76  97]
 [ 14  52 100  29  51  86  49  33  56  69]
 [ 34   5  30  58   0  82  71  18  95  53]
 [  4  13  10  85  49  52  77  38  50  82]
 [ 12  90  75  25  87  40   8   2  97   5]
 [ 15  54  91  42  82  88  25  47  64   3]
 [  9  36  52   7  42  83  38  78   5  13]
 [ 46  22  62   7  79  33  92   4  89  41]
 [ 10  25  89  96  52  98  79  96  74   9]] (10, 10)
min = 0, max = 100


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [10]:
arr = np.random.randint(101, size= 30)
print(arr, arr.size)
print(f"mean = {arr.mean()}")

[  7  99  50  76  36  39 100  70  86  42  83  61  10  30  53  62  53  28
   0  88  38   0  63  59  18  27  26  10   0  49] 30
mean = 45.43333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [11]:
arr = np.ones((4,4))
arr[1:3, 1:3] = np.zeros((2,2))
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [12]:
arr = np.random.randint(101, size = (4,4))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr)

[[  0   0   0   0   0   0]
 [  0  46   2  20  22   0]
 [  0  97  78  94  79   0]
 [  0  39  13  90 100   0]
 [  0  10  29  76  98   0]
 [  0   0   0   0   0   0]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [13]:
# 0 * np.nan  # nan
# np.nan == np.nan  # False
# np.inf > np.nan  # False
# np.nan - np.nan  # nan
# np.nan in set([np.nan])  # True 
# 0.3 == 3 * 0.1  # False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
arr = np.random.randint(1, 5, size = (5,5))
arr = np.tril(arr, -1)
print(arr)

[[0 0 0 0 0]
 [3 0 0 0 0]
 [4 4 0 0 0]
 [4 1 1 0 0]
 [3 3 3 3 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [15]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
arr = np.random.randint(101, size = (5,5))
arr = np.linalg.norm(arr)
print(arr)

279.3313444638822


In [17]:
arr = np.random.randint(101, size = (5,5))
print(arr,"\n")
row_sums = arr.sum(axis=1, keepdims=True)
arr = arr / row_sums[:,:]
print(arr)

[[57 45 38 27 87]
 [10 39 98 48 39]
 [ 4 19 34 96 53]
 [81 90  6 80 34]
 [ 8 65 46 18 94]] 

[[0.22440945 0.17716535 0.1496063  0.10629921 0.34251969]
 [0.04273504 0.16666667 0.41880342 0.20512821 0.16666667]
 [0.01941748 0.09223301 0.16504854 0.46601942 0.25728155]
 [0.27835052 0.30927835 0.02061856 0.27491409 0.11683849]
 [0.03463203 0.28138528 0.1991342  0.07792208 0.40692641]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
arr = np.arange(10)
print(arr)
arr[4:8] = np.zeros(4) 
print(arr)
arr = np.delete(arr, np.s_[4:8])
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 0 0 0 0 8 9]
[0 1 2 3 8 9]


#### 29. How to round away from zero a float array ? (★☆☆)

In [19]:
arr = np.array([1.1,2.7,3.4,4.5,5.3], dtype='float')
arr = np.ceil(arr)
print(arr)

[2. 3. 4. 5. 6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [20]:
arr1 = np.array([2,6,3,8,5])
arr2 = np.array([1,4,6,7,2])

print(np.intersect1d(arr1,arr2))

[2 6]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [21]:
# False, np.sqrt(-1) will return nan

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [22]:
iterable = (x*x for x in range(10))
arr = np.fromiter(iterable, dtype= 'int16')
print(arr)

[ 0  1  4  9 16 25 36 49 64 81]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [23]:
arr = np.linspace(0, 1, num=11, endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [24]:
arr = np.random.randint(101, size=10)
print(arr)
arr = np.sort(arr)
print(arr)

[70  1 46 40 29 95 79 80 81 64]
[ 1 29 40 46 64 70 79 80 81 95]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [25]:
arr1 = np.random.randint(6, size=5)
arr2 = np.random.randint(6, size=5)
print(arr1, arr2)
print(np.array_equal(arr1, arr2))

[4 5 0 3 5] [0 4 1 4 5]
False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [26]:
arr = np.random.randint(11, size=10)
print(arr)
max_index = np.argmax(arr)
arr[max_index] = 0
print(arr)

[ 9  3  5  5  0  6 10  5  0  5]
[9 3 5 5 0 6 0 5 0 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [27]:
def find_nearest(array, scalar):
    arr = np.asarray(array)  # Convert input into an array
    index = (np.abs(arr - scalar)).argmin()  # The smallest absoulte difference represents the closest value
    return arr[index]

arr = np.random.randint(101, size=10)
print(arr)
print(find_nearest(arr, 42))

[25 70 54 11 73 61  8 52 33  2]
33


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [28]:
arr = np.array([1,2,3,4], dtype='float32')
print(arr, arr.dtype)
arr = arr.astype(dtype='int32', copy=False)
print(arr, arr.dtype)

[1. 2. 3. 4.] float32
[1 2 3 4] int32


#### 59. How to sort an array by the nth column? (★★☆)

In [29]:
arr = np.random.randint(11, size=(3,3))
print(arr)
ai = np.argsort(arr, axis=0)
arr = np.take_along_axis(arr,ai,axis=0)
print(arr)

[[ 3 10  4]
 [ 7  4  5]
 [ 5  7  6]]
[[ 3  4  4]
 [ 5  7  5]
 [ 7 10  6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [30]:
arr = np.array([[1,2,3],[0,0,0],[4,5,6]]).transpose()
print(arr)
arr = ~(np.any(arr,axis=0))
print(arr)

[[1 0 4]
 [2 0 5]
 [3 0 6]]
[False  True False]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [64]:
arr = np.array([1,2,3,4,5])
inter_arr = np.zeros((3 * arr.size), dtype='int64')
idx = tuple(range(0,inter_arr.size,3)) 
inter_arr = np.insert(inter_arr, idx, arr)[np.s_[:-3]]
print(inter_arr)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,"\n\n")
arr[[0,2]] = arr[[2,0]]  # arr[[0,2]] is equivalent to arr[[0,2], :] so a submatrix 
                         # consisting of rows 0 and 2 are selected.
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 


[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [76]:
arr = np.array([True, True, False, True, False])
np.logical_not(arr, out=arr)
print(arr)

arr = np.array([5.5, -6.6, -7.7, 2.1, -3.3])
np.negative(arr, out=arr)
print(arr)

[False False  True False  True]
[-5.5  6.6  7.7 -2.1  3.3]


#### 83. How to find the most frequent value in an array?

In [79]:
arr = np.random.randint(-10, 11, size=(10,10))
print(arr)

values, counts = np.unique(arr, return_counts=True)
most_freq_idx = counts.argmax()
print(f"Most frequent value in the array is {values[most_freq_idx]}")

[[  9   5  -2   1  -7   9  -6   9  -2   5]
 [  0   9 -10  -3   5   7   7 -10  -9  -3]
 [  2   6 -10  -7   0  -9  -4  -3   3  -9]
 [ -7  -5   7  -7  10  -8   3   2 -10  -1]
 [-10  -2   5   4   4   0   2 -10   6  -1]
 [ -5 -10   5  -9   8 -10  -9  -7  -2   0]
 [  8   5  -2   1   3   0   9   0  -4  -2]
 [  1  -7   2  -6  -8  -8   0   8  -1  -5]
 [  7   7  -1  -9   0   2  -4   7   1  -3]
 [ -5   4  -1  10 -10  -9 -10   4   7  10]]
Most frequent value in the array is -10


#### 89. How to get the n largest values of an array (★★★)

In [87]:
arr = np.random.randint(0, 51, size=100)
print(arr)

max_vals = np.sort(arr)[-5:]
print(max_vals)

# Note: for n largest UNIQUE values use np.unique before sorting.

[42 14 33 37 21 42 23 27 34 22  4 35 37 20 16 17  2 16 17 19 41 22 33 37
 28 33 33 16 36 27 38 39 11 43  7 11 20 15 45 20  8 14 30 48 21 25 11 38
 32 46 36 43 42 23 35 26 42 19 40 40 24 32 32 24 44 50 27 25 30 13 45  7
 24 16 17  1 37 32  6 34 23 26 12 34 13  4 31 35 10  2 30 43 15 48 46  6
  6 37 46 36]
[46 46 48 48 50]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [88]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[0,0,0]])
print(arr)
print(np.unique(arr, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [0 0 0]]
[[0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
