In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [3]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(type(x),type(A))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
print(A.shape,x.shape)

(3, 2) (4,)


In [6]:
print(A.T)
print(A.transpose())

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


### Matrix Addition

In [7]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [8]:
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [9]:
D = A + 1
D

array([[2, 3],
       [4, 5],
       [6, 7]])

In [10]:
# Broadcasting
# Broadcasting works only if the first array has the same number of rows as the second one, and one of the arrays has only one column
E = np.array([[1],[2],[3]])
print(E)
F = A + E
F

[[1]
 [2]
 [3]]


array([[2, 3],
       [5, 6],
       [8, 9]])

### Matrix Multiplication

In [11]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4]])

C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [12]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

### Identity Matrix

In [13]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# I.A = A
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Determinant

In [15]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [16]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

### Inverse Matrices

In [17]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [18]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [19]:
I = A.dot(A_inv)
I

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])